# Generated by Django 4.1.6 on 2023-04-17 17:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articles",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(default="", editable=False, max_length=200)),
                ("body", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("update_at", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(blank=True, upload_to="article_images")),
            ],
        ),
    ]
