# Generated by Django 4.2 on 2023-04-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="nb_articles",
            field=models.IntegerField(default=0),
        ),
    ]
