# Generated by Django 4.2 on 2023-04-18 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_cust", "0007_remove_blogger_username_customuser_username_and_more"),
        ("articles", "0003_articles_nb_articles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articles",
            name="user",
        ),
        migrations.AddField(
            model_name="articles",
            name="blogger",
            field=models.ForeignKey(
                default="",
                limit_choices_to={"is_staff": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="user_cust.blogger",
            ),
        ),
    ]
