# Generated by Django 4.2 on 2023-04-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_cust", "0002_alter_blogger_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogger",
            name="bio",
            field=models.CharField(
                default="Hello Je m'appelle <django.db.models.fields.CharField> et j'ecris des articles sur mon apprentissage du framework Django",
                max_length=200,
            ),
        ),
    ]
