# Generated by Django 4.2 on 2023-04-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_cust", "0003_blogger_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogger",
            name="email",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Adresse Email"
            ),
        ),
    ]
