# Generated by Django 4.2 on 2023-04-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_cust", "0004_remove_blogger_email_remove_customuser_username_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
