# Generated by Django 4.2 on 2023-04-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_cust", "0007_remove_blogger_username_customuser_username_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="last_name",
        ),
    ]
